## HTTP configuration
quarkus.http.port=8082
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.rest-client.hero.url=http://localhost:8083
quarkus.rest-client.villain.url=http://localhost:8084

## Logging configuration
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

## Custom banner file path
quarkus.banner.path=banner.txt

# Database settings DEV
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/villains_db
quarkus.datasource.username=dev
quarkus.datasource.password=dev
quarkus.log.console.level=DEBUG
quarkus.hibernate-orm.sql-load-script=import.sql

# Database settings PROD
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/villains_db
%prod.quarkus.datasource.username=dev
%prod.quarkus.datasource.password=dev
%prod.quarkus.log.console.level=INFO
%prod.quarkus.hibernate-orm.sql-load-script=import.sql

# Database settings (usar "drop-and-create" para rodar o import.sql pela 1 vez)
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.datasource.devservices.enabled=false

mp.messaging.incoming.words-in.auto.offset.reset=earliest
mp.messaging.incoming.words-in.topic=words
mp.messaging.outgoing.words-out.topic=words

# Database settings tests
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.kafka.devservices.enabled=false
quarkus.kafka.devservices.enabled=false
%test.quarkus.hibernate-orm.sql-load-script=import.sql
