## HTTP configuration
quarkus.http.port=8084

quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=INFO
quarkus.log.console.darken=1

# Database settings DEV
quarkus.datasource.username=dev
quarkus.datasource.password=dev
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/villains_db

# Database settings PROD
%prod.quarkus.datasource.username=dev
%prod.quarkus.datasource.password=dev
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/villains_db
%prod.quarkus.hibernate-orm.sql-load-script=import.sql

# Database settings (usar "drop-and-create" para rodar o import.sql)
quarkus.hibernate-orm.database.generation=update

# Project settings
level.multiplier=1

# Project Tests
%test.level.multiplier=1
