## HTTP configuration
quarkus.http.port=8083
quarkus.http.cors=true

quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.darken=1

# Database settings DEV
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://localhost:5432/villains_db
quarkus.datasource.username=dev
quarkus.datasource.password=dev
quarkus.log.console.level=DEBUG
quarkus.hibernate-orm.sql-load-script=import.sql

# Database settings PROD
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.reactive.url=postgresql://localhost:5432/villains_db
%prod.quarkus.datasource.username=dev
%prod.quarkus.datasource.password=dev
%prod.quarkus.log.console.level=INFO
%prod.quarkus.hibernate-orm.sql-load-script=import.sql

# Database settings (usar "drop-and-create" para rodar o import.sql pela 1 vez)
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.devservices.enabled=false

# Database settings tests
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=import.sql
